using System.ComponentModel.DataAnnotations.Schema;

namespace ZenGear.Domain.Common;

/// <summary>
/// Base entity with internal Id (long) and external Id (string).
/// Use for entities that are exposed via API.
/// </summary>
public abstract class BaseEntity
{
    /// <summary>
    /// Internal database identifier (BIGSERIAL in PostgreSQL).
    /// Used for JOINs, FKs, indexes. NEVER expose in API.
    /// </summary>
    public long Id { get; private set; }

    /// <summary>
    /// External identifier for API responses.
    /// Format: {prefix}_{nanoid16} (e.g., usr_V1StGXR8Z5jdHi6B)
    /// This is what clients see as "id" in JSON responses.
    /// </summary>
    public string ExternalId { get; private set; } = null!;

    private readonly List<IDomainEvent> _domainEvents = [];

    /// <summary>
    /// Domain events raised by this entity.
    /// Events are dispatched after SaveChanges succeeds.
    /// </summary>
    [NotMapped]
    public IReadOnlyList<IDomainEvent> DomainEvents => _domainEvents.AsReadOnly();

    /// <summary>
    /// EF Core constructor (required).
    /// </summary>
    protected BaseEntity() { }

    /// <summary>
    /// Set external ID. Should be called once during entity creation.
    /// </summary>
    /// <param name="externalId">External ID generated by IExternalIdGenerator</param>
    /// <exception cref="ArgumentException">If external ID is null or whitespace</exception>
    protected internal void SetExternalId(string externalId)
    {
        if (string.IsNullOrWhiteSpace(externalId))
            throw new ArgumentException("External ID cannot be empty.", nameof(externalId));

        ExternalId = externalId;
    }

    /// <summary>
    /// Add a domain event to be dispatched after SaveChanges.
    /// </summary>
    public void AddDomainEvent(IDomainEvent domainEvent)
    {
        _domainEvents.Add(domainEvent);
    }

    /// <summary>
    /// Remove a specific domain event.
    /// </summary>
    public void RemoveDomainEvent(IDomainEvent domainEvent)
    {
        _domainEvents.Remove(domainEvent);
    }

    /// <summary>
    /// Clear all domain events.
    /// Called automatically after events are dispatched.
    /// </summary>
    public void ClearDomainEvents()
    {
        _domainEvents.Clear();
    }
}
